// This file is generated by scripts/generate-trip-media.mjs.
// Run npm run generate:media after changing public/trips files.

export type GeneratedTripMedia = {
  type: "image" | "video";
  src: string;
  alt: string;
};

export const tripMedia: Record<string, GeneratedTripMedia[]> = {
  "alcatraz": [
    {
      "type": "video",
      "src": "/trips/alcatraz/A4D1ECD0-3DD2-4E91-91DB-31B29003C845.mov",
      "alt": "A4D1ECD0 3DD2 4E91 91DB 31B29003C845"
    },
    {
      "type": "image",
      "src": "/trips/alcatraz/IMG_3965.JPG",
      "alt": "IMG 3965"
    },
    {
      "type": "image",
      "src": "/trips/alcatraz/IMG_3970.JPG",
      "alt": "IMG 3970"
    },
    {
      "type": "image",
      "src": "/trips/alcatraz/IMG_4616.jpeg",
      "alt": "IMG 4616"
    },
    {
      "type": "image",
      "src": "/trips/alcatraz/IMG_4620.jpeg",
      "alt": "IMG 4620"
    },
    {
      "type": "image",
      "src": "/trips/alcatraz/IMG_4622.jpeg",
      "alt": "IMG 4622"
    },
    {
      "type": "image",
      "src": "/trips/alcatraz/IMG_4623.jpeg",
      "alt": "IMG 4623"
    },
    {
      "type": "image",
      "src": "/trips/alcatraz/IMG_4625.jpeg",
      "alt": "IMG 4625"
    },
    {
      "type": "image",
      "src": "/trips/alcatraz/IMG_4626.jpeg",
      "alt": "IMG 4626"
    },
    {
      "type": "image",
      "src": "/trips/alcatraz/IMG_4629.jpeg",
      "alt": "IMG 4629"
    },
    {
      "type": "image",
      "src": "/trips/alcatraz/IMG_4631.JPG",
      "alt": "IMG 4631"
    },
    {
      "type": "video",
      "src": "/trips/alcatraz/IMG_4633.mov",
      "alt": "IMG 4633"
    },
    {
      "type": "image",
      "src": "/trips/alcatraz/IMG_4636.jpeg",
      "alt": "IMG 4636"
    }
  ],
  "amsterdam": [
    {
      "type": "video",
      "src": "/trips/amsterdam/A96F33D2-B8C7-4F2A-A657-7FC06DA9F074.mov",
      "alt": "A96F33D2 B8C7 4F2A A657 7FC06DA9F074"
    },
    {
      "type": "video",
      "src": "/trips/amsterdam/D986C27F-E007-4A9A-AE4B-0D2B2B58B9F1.mov",
      "alt": "D986C27F E007 4A9A AE4B 0D2B2B58B9F1"
    },
    {
      "type": "video",
      "src": "/trips/amsterdam/filtered-F9CF3C0D-C85F-493B-AAD8-2C51503F7EFD.mov",
      "alt": "filtered F9CF3C0D C85F 493B AAD8 2C51503F7EFD"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_5536.JPG",
      "alt": "IMG 5536"
    },
    {
      "type": "video",
      "src": "/trips/amsterdam/IMG_5537.mov",
      "alt": "IMG 5537"
    },
    {
      "type": "video",
      "src": "/trips/amsterdam/IMG_7125.mov",
      "alt": "IMG 7125"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7134.JPG",
      "alt": "IMG 7134"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7161.jpeg",
      "alt": "IMG 7161"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7170.jpeg",
      "alt": "IMG 7170"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7181.jpeg",
      "alt": "IMG 7181"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7183.jpeg",
      "alt": "IMG 7183"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7187.jpeg",
      "alt": "IMG 7187"
    },
    {
      "type": "video",
      "src": "/trips/amsterdam/IMG_7189.mov",
      "alt": "IMG 7189"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7195.jpeg",
      "alt": "IMG 7195"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7203.jpeg",
      "alt": "IMG 7203"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7207.jpeg",
      "alt": "IMG 7207"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7212.jpeg",
      "alt": "IMG 7212"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7215.jpeg",
      "alt": "IMG 7215"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7220.jpeg",
      "alt": "IMG 7220"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7229.jpeg",
      "alt": "IMG 7229"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7237.jpeg",
      "alt": "IMG 7237"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7239.jpeg",
      "alt": "IMG 7239"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7240.jpeg",
      "alt": "IMG 7240"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7244.jpeg",
      "alt": "IMG 7244"
    },
    {
      "type": "image",
      "src": "/trips/amsterdam/IMG_7247.jpeg",
      "alt": "IMG 7247"
    }
  ],
  "bay-area": [
    {
      "type": "image",
      "src": "/trips/bay-area/IMG_0010.JPG",
      "alt": "IMG 0010"
    },
    {
      "type": "video",
      "src": "/trips/bay-area/IMG_0010.MP4",
      "alt": "IMG 0010"
    },
    {
      "type": "image",
      "src": "/trips/bay-area/IMG_0014.JPG",
      "alt": "IMG 0014"
    },
    {
      "type": "video",
      "src": "/trips/bay-area/IMG_0014.MP4",
      "alt": "IMG 0014"
    },
    {
      "type": "image",
      "src": "/trips/bay-area/IMG_0034.JPG",
      "alt": "IMG 0034"
    },
    {
      "type": "video",
      "src": "/trips/bay-area/IMG_0034.MP4",
      "alt": "IMG 0034"
    },
    {
      "type": "image",
      "src": "/trips/bay-area/IMG_0490.JPG",
      "alt": "IMG 0490"
    },
    {
      "type": "image",
      "src": "/trips/bay-area/IMG_0496.JPG",
      "alt": "IMG 0496"
    },
    {
      "type": "image",
      "src": "/trips/bay-area/IMG_0528.JPG",
      "alt": "IMG 0528"
    },
    {
      "type": "image",
      "src": "/trips/bay-area/IMG_0539.JPG",
      "alt": "IMG 0539"
    },
    {
      "type": "image",
      "src": "/trips/bay-area/IMG_0556.JPG",
      "alt": "IMG 0556"
    },
    {
      "type": "image",
      "src": "/trips/bay-area/IMG_0560.JPG",
      "alt": "IMG 0560"
    },
    {
      "type": "image",
      "src": "/trips/bay-area/IMG_0576.JPG",
      "alt": "IMG 0576"
    },
    {
      "type": "video",
      "src": "/trips/bay-area/IMG_0576.MP4",
      "alt": "IMG 0576"
    },
    {
      "type": "video",
      "src": "/trips/bay-area/IMG_0694.MP4",
      "alt": "IMG 0694"
    },
    {
      "type": "video",
      "src": "/trips/bay-area/IMG_4335.MP4",
      "alt": "IMG 4335"
    },
    {
      "type": "video",
      "src": "/trips/bay-area/IMG_4448.MP4",
      "alt": "IMG 4448"
    },
    {
      "type": "video",
      "src": "/trips/bay-area/lp_image.MP4",
      "alt": "lp image"
    }
  ],
  "cabo": [
    {
      "type": "image",
      "src": "/trips/cabo/IMG_3665.JPG",
      "alt": "IMG 3665"
    },
    {
      "type": "image",
      "src": "/trips/cabo/IMG_3670.JPG",
      "alt": "IMG 3670"
    },
    {
      "type": "image",
      "src": "/trips/cabo/IMG_3687.JPG",
      "alt": "IMG 3687"
    },
    {
      "type": "video",
      "src": "/trips/cabo/IMG_3696.mov",
      "alt": "IMG 3696"
    },
    {
      "type": "video",
      "src": "/trips/cabo/IMG_4001 2.mov",
      "alt": "IMG 4001 2"
    },
    {
      "type": "video",
      "src": "/trips/cabo/IMG_4001.mov",
      "alt": "IMG 4001"
    },
    {
      "type": "video",
      "src": "/trips/cabo/IMG_4002.mov",
      "alt": "IMG 4002"
    },
    {
      "type": "image",
      "src": "/trips/cabo/IMG_4030.jpeg",
      "alt": "IMG 4030"
    },
    {
      "type": "image",
      "src": "/trips/cabo/IMG_4087.jpeg",
      "alt": "IMG 4087"
    },
    {
      "type": "video",
      "src": "/trips/cabo/IMG_4095.mov",
      "alt": "IMG 4095"
    },
    {
      "type": "image",
      "src": "/trips/cabo/IMG_4101.jpeg",
      "alt": "IMG 4101"
    },
    {
      "type": "image",
      "src": "/trips/cabo/IMG_4112.jpeg",
      "alt": "IMG 4112"
    },
    {
      "type": "image",
      "src": "/trips/cabo/IMG_4173.jpeg",
      "alt": "IMG 4173"
    },
    {
      "type": "video",
      "src": "/trips/cabo/IMG_4198.mov",
      "alt": "IMG 4198"
    },
    {
      "type": "image",
      "src": "/trips/cabo/IMG_4209.jpeg",
      "alt": "IMG 4209"
    }
  ],
  "chicago": [
    {
      "type": "image",
      "src": "/trips/chicago/IMG_0008.JPG",
      "alt": "IMG 0008"
    },
    {
      "type": "video",
      "src": "/trips/chicago/IMG_0008.MP4",
      "alt": "IMG 0008"
    },
    {
      "type": "image",
      "src": "/trips/chicago/IMG_0009.JPG",
      "alt": "IMG 0009"
    },
    {
      "type": "video",
      "src": "/trips/chicago/IMG_0009.MP4",
      "alt": "IMG 0009"
    },
    {
      "type": "image",
      "src": "/trips/chicago/IMG_0017.JPG",
      "alt": "IMG 0017"
    },
    {
      "type": "video",
      "src": "/trips/chicago/IMG_0017.MP4",
      "alt": "IMG 0017"
    },
    {
      "type": "image",
      "src": "/trips/chicago/IMG_0019.JPG",
      "alt": "IMG 0019"
    },
    {
      "type": "video",
      "src": "/trips/chicago/IMG_0019.MP4",
      "alt": "IMG 0019"
    },
    {
      "type": "image",
      "src": "/trips/chicago/IMG_8758.JPG",
      "alt": "IMG 8758"
    },
    {
      "type": "video",
      "src": "/trips/chicago/IMG_8758.MP4",
      "alt": "IMG 8758"
    },
    {
      "type": "image",
      "src": "/trips/chicago/IMG_8763.JPG",
      "alt": "IMG 8763"
    },
    {
      "type": "image",
      "src": "/trips/chicago/IMG_8779.JPG",
      "alt": "IMG 8779"
    },
    {
      "type": "image",
      "src": "/trips/chicago/IMG_8782.JPG",
      "alt": "IMG 8782"
    },
    {
      "type": "image",
      "src": "/trips/chicago/IMG_8788.JPG",
      "alt": "IMG 8788"
    },
    {
      "type": "image",
      "src": "/trips/chicago/IMG_8790.JPG",
      "alt": "IMG 8790"
    },
    {
      "type": "image",
      "src": "/trips/chicago/IMG_8795.JPG",
      "alt": "IMG 8795"
    },
    {
      "type": "image",
      "src": "/trips/chicago/IMG_8796.JPG",
      "alt": "IMG 8796"
    },
    {
      "type": "image",
      "src": "/trips/chicago/IMG_8806.JPG",
      "alt": "IMG 8806"
    },
    {
      "type": "image",
      "src": "/trips/chicago/IMG_8808.JPG",
      "alt": "IMG 8808"
    },
    {
      "type": "image",
      "src": "/trips/chicago/IMG_8815.JPG",
      "alt": "IMG 8815"
    }
  ],
  "denver": [
    {
      "type": "video",
      "src": "/trips/denver/6CF2EC3B-7EA9-4539-BD4D-67D4BA9B00FD.mov",
      "alt": "CF2EC3B 7EA9 4539 BD4D 67D4BA9B00FD"
    },
    {
      "type": "video",
      "src": "/trips/denver/IMG_3696.mov",
      "alt": "IMG 3696"
    },
    {
      "type": "image",
      "src": "/trips/denver/IMG_4382.jpeg",
      "alt": "IMG 4382"
    },
    {
      "type": "image",
      "src": "/trips/denver/IMG_4390.jpeg",
      "alt": "IMG 4390"
    },
    {
      "type": "image",
      "src": "/trips/denver/IMG_4396.jpeg",
      "alt": "IMG 4396"
    },
    {
      "type": "image",
      "src": "/trips/denver/IMG_4405.jpeg",
      "alt": "IMG 4405"
    },
    {
      "type": "image",
      "src": "/trips/denver/IMG_4410.jpeg",
      "alt": "IMG 4410"
    },
    {
      "type": "video",
      "src": "/trips/denver/IMG_4413.mov",
      "alt": "IMG 4413"
    },
    {
      "type": "image",
      "src": "/trips/denver/IMG_4415.jpeg",
      "alt": "IMG 4415"
    }
  ],
  "flying-in-sf": [
    {
      "type": "video",
      "src": "/trips/flying-in-sf/6F172E8B-D8FB-4F9D-BB48-6EA3B9E52AF3.mov",
      "alt": "F172E8B D8FB 4F9D BB48 6EA3B9E52AF3"
    },
    {
      "type": "image",
      "src": "/trips/flying-in-sf/IMG_4310.JPG",
      "alt": "IMG 4310"
    },
    {
      "type": "video",
      "src": "/trips/flying-in-sf/IMG_5280.mov",
      "alt": "IMG 5280"
    },
    {
      "type": "image",
      "src": "/trips/flying-in-sf/IMG_5294.jpeg",
      "alt": "IMG 5294"
    },
    {
      "type": "image",
      "src": "/trips/flying-in-sf/IMG_5309.jpeg",
      "alt": "IMG 5309"
    },
    {
      "type": "video",
      "src": "/trips/flying-in-sf/IMG_5317.mov",
      "alt": "IMG 5317"
    },
    {
      "type": "image",
      "src": "/trips/flying-in-sf/IMG_5319.jpeg",
      "alt": "IMG 5319"
    },
    {
      "type": "video",
      "src": "/trips/flying-in-sf/IMG_5324.mov",
      "alt": "IMG 5324"
    },
    {
      "type": "image",
      "src": "/trips/flying-in-sf/IMG_5330.jpeg",
      "alt": "IMG 5330"
    },
    {
      "type": "image",
      "src": "/trips/flying-in-sf/IMG_5331.jpeg",
      "alt": "IMG 5331"
    },
    {
      "type": "image",
      "src": "/trips/flying-in-sf/IMG_5335.JPG",
      "alt": "IMG 5335"
    },
    {
      "type": "image",
      "src": "/trips/flying-in-sf/IMG_5340.jpeg",
      "alt": "IMG 5340"
    },
    {
      "type": "image",
      "src": "/trips/flying-in-sf/IMG_5348.jpeg",
      "alt": "IMG 5348"
    }
  ],
  "london": [
    {
      "type": "video",
      "src": "/trips/london/1CBBDABA-078B-4EAD-81CE-F82989C90C25.MP4",
      "alt": "CBBDABA 078B 4EAD 81CE F82989C90C25"
    },
    {
      "type": "image",
      "src": "/trips/london/07E9BB2B-5358-41C8-922C-E62117A62EE5_1_105_c.jpeg",
      "alt": "E9BB2B 5358 41C8 922C E62117A62EE5 1 105 c"
    },
    {
      "type": "image",
      "src": "/trips/london/8B74042A-ADEF-4F92-9796-6DC84CE3CD9D_1_105_c.jpeg",
      "alt": "B74042A ADEF 4F92 9796 6DC84CE3CD9D 1 105 c"
    },
    {
      "type": "image",
      "src": "/trips/london/8D691ED0-6E80-46D1-BE12-7666CFC491EB_1_105_c.jpeg",
      "alt": "D691ED0 6E80 46D1 BE12 7666CFC491EB 1 105 c"
    },
    {
      "type": "image",
      "src": "/trips/london/9AB147F7-F7C1-4FAE-A79A-CDB934EB0DFE_1_105_c.jpeg",
      "alt": "AB147F7 F7C1 4FAE A79A CDB934EB0DFE 1 105 c"
    },
    {
      "type": "image",
      "src": "/trips/london/583C9A19-A0B2-45DB-BEA1-D01D60F9BE3F_4_5005_c.jpeg",
      "alt": "C9A19 A0B2 45DB BEA1 D01D60F9BE3F 4 5005 c"
    },
    {
      "type": "image",
      "src": "/trips/london/588F22DA-71EC-4F74-B5BC-2A8F7CF48F08_1_105_c.jpeg",
      "alt": "F22DA 71EC 4F74 B5BC 2A8F7CF48F08 1 105 c"
    },
    {
      "type": "image",
      "src": "/trips/london/5032C80A-BD90-40D3-B7C4-4336EBF8F5F0_1_105_c.jpeg",
      "alt": "C80A BD90 40D3 B7C4 4336EBF8F5F0 1 105 c"
    },
    {
      "type": "image",
      "src": "/trips/london/A40CC524-1AE3-40EF-9BEF-F088E66DADAD_1_105_c.jpeg",
      "alt": "A40CC524 1AE3 40EF 9BEF F088E66DADAD 1 105 c"
    },
    {
      "type": "image",
      "src": "/trips/london/B5DC15C9-3E08-437C-8ACA-F97B8D17BF14_1_105_c.jpeg",
      "alt": "B5DC15C9 3E08 437C 8ACA F97B8D17BF14 1 105 c"
    },
    {
      "type": "image",
      "src": "/trips/london/C16FD88E-1AD7-4ACE-A8DC-F9909BE29E68_1_105_c.jpeg",
      "alt": "C16FD88E 1AD7 4ACE A8DC F9909BE29E68 1 105 c"
    },
    {
      "type": "image",
      "src": "/trips/london/F62967E2-42E2-404D-8F9D-0D7786C26EA5_1_105_c.jpeg",
      "alt": "F62967E2 42E2 404D 8F9D 0D7786C26EA5 1 105 c"
    },
    {
      "type": "image",
      "src": "/trips/london/FBBC60B3-6A7D-4AFA-9601-E320ABE44060_4_5005_c.jpeg",
      "alt": "FBBC60B3 6A7D 4AFA 9601 E320ABE44060 4 5005 c"
    },
    {
      "type": "video",
      "src": "/trips/london/IMG_3113.MP4",
      "alt": "IMG 3113"
    },
    {
      "type": "video",
      "src": "/trips/london/IMG_3194.MP4",
      "alt": "IMG 3194"
    },
    {
      "type": "video",
      "src": "/trips/london/m1sYAOIC.MP4",
      "alt": "m1sYAOIC"
    }
  ],
  "mount-tamalpais": [
    {
      "type": "image",
      "src": "/trips/mount-tamalpais/2D57E7F5-5670-410B-BFFC-DB806977E5DE.jpeg",
      "alt": "D57E7F5 5670 410B BFFC DB806977E5DE"
    },
    {
      "type": "image",
      "src": "/trips/mount-tamalpais/006A27F1-DB4C-481A-B725-E9BDAAE2E16C.jpeg",
      "alt": "A27F1 DB4C 481A B725 E9BDAAE2E16C"
    },
    {
      "type": "image",
      "src": "/trips/mount-tamalpais/20B22C87-2B13-416C-BBAB-A30179241B6A.jpeg",
      "alt": "B22C87 2B13 416C BBAB A30179241B6A"
    },
    {
      "type": "image",
      "src": "/trips/mount-tamalpais/4832C36F-048F-4E28-A743-1C7DAC963ADC.jpeg",
      "alt": "C36F 048F 4E28 A743 1C7DAC963ADC"
    },
    {
      "type": "image",
      "src": "/trips/mount-tamalpais/184662D4-3CB8-4916-94A7-AE1DB5645016.jpeg",
      "alt": "D4 3CB8 4916 94A7 AE1DB5645016"
    },
    {
      "type": "image",
      "src": "/trips/mount-tamalpais/54269353-C2D3-4E32-9366-C1099E4E223F.jpeg",
      "alt": "C2D3 4E32 9366 C1099E4E223F"
    },
    {
      "type": "image",
      "src": "/trips/mount-tamalpais/C3FBD852-D280-42F3-8224-08B9FD8E2A2A.jpeg",
      "alt": "C3FBD852 D280 42F3 8224 08B9FD8E2A2A"
    },
    {
      "type": "image",
      "src": "/trips/mount-tamalpais/C46D6C79-D3ED-4B0B-AE8B-16E46DA3A979.jpeg",
      "alt": "C46D6C79 D3ED 4B0B AE8B 16E46DA3A979"
    },
    {
      "type": "image",
      "src": "/trips/mount-tamalpais/CD05214B-2753-45E4-B098-2AD721104A42.jpeg",
      "alt": "CD05214B 2753 45E4 B098 2AD721104A42"
    },
    {
      "type": "image",
      "src": "/trips/mount-tamalpais/E9F086FE-74AB-4B37-A0F4-7B881B7AA7A6.jpeg",
      "alt": "E9F086FE 74AB 4B37 A0F4 7B881B7AA7A6"
    },
    {
      "type": "image",
      "src": "/trips/mount-tamalpais/F7CDC79A-B807-4D98-BA98-9F574595B082.jpeg",
      "alt": "F7CDC79A B807 4D98 BA98 9F574595B082"
    },
    {
      "type": "video",
      "src": "/trips/mount-tamalpais/IMG_3438.MP4",
      "alt": "IMG 3438"
    },
    {
      "type": "video",
      "src": "/trips/mount-tamalpais/IMG_3453.MP4",
      "alt": "IMG 3453"
    },
    {
      "type": "video",
      "src": "/trips/mount-tamalpais/IMG_3467.MP4",
      "alt": "IMG 3467"
    }
  ],
  "nasa-launch-orlando": [
    {
      "type": "video",
      "src": "/trips/nasa-launch-orlando/5CC3A611-6213-4661-A5E7-D7D6CAFCCCE6 (1).mp4",
      "alt": "CC3A611 6213 4661 A5E7 D7D6CAFCCCE6 (1)"
    },
    {
      "type": "image",
      "src": "/trips/nasa-launch-orlando/4881EA76-6187-4A62-9022-27F5364442F7.JPG",
      "alt": "EA76 6187 4A62 9022 27F5364442F7"
    },
    {
      "type": "video",
      "src": "/trips/nasa-launch-orlando/D0B177D0-0285-482D-B1A5-E416F33BC800.MP4",
      "alt": "D0B177D0 0285 482D B1A5 E416F33BC800"
    },
    {
      "type": "video",
      "src": "/trips/nasa-launch-orlando/IMG_5847.mov",
      "alt": "IMG 5847"
    },
    {
      "type": "image",
      "src": "/trips/nasa-launch-orlando/IMG_5851.jpeg",
      "alt": "IMG 5851"
    },
    {
      "type": "image",
      "src": "/trips/nasa-launch-orlando/IMG_5856.JPG",
      "alt": "IMG 5856"
    },
    {
      "type": "image",
      "src": "/trips/nasa-launch-orlando/IMG_5857.jpeg",
      "alt": "IMG 5857"
    }
  ],
  "new-york": [
    {
      "type": "video",
      "src": "/trips/new-york/3D9BC389-A101-4E29-9F6F-D04AA5081505.mov",
      "alt": "D9BC389 A101 4E29 9F6F D04AA5081505"
    },
    {
      "type": "image",
      "src": "/trips/new-york/FullSizeRender.jpeg",
      "alt": "FullSizeRender"
    },
    {
      "type": "video",
      "src": "/trips/new-york/IMG_5705.mov",
      "alt": "IMG 5705"
    },
    {
      "type": "image",
      "src": "/trips/new-york/IMG_5710.jpeg",
      "alt": "IMG 5710"
    },
    {
      "type": "image",
      "src": "/trips/new-york/IMG_5711.jpeg",
      "alt": "IMG 5711"
    },
    {
      "type": "video",
      "src": "/trips/new-york/IMG_5718.mov",
      "alt": "IMG 5718"
    },
    {
      "type": "image",
      "src": "/trips/new-york/IMG_5726.jpeg",
      "alt": "IMG 5726"
    },
    {
      "type": "image",
      "src": "/trips/new-york/IMG_5741.jpeg",
      "alt": "IMG 5741"
    },
    {
      "type": "image",
      "src": "/trips/new-york/IMG_5748.JPG",
      "alt": "IMG 5748"
    },
    {
      "type": "image",
      "src": "/trips/new-york/IMG_5754.jpeg",
      "alt": "IMG 5754"
    },
    {
      "type": "image",
      "src": "/trips/new-york/IMG_5767.jpeg",
      "alt": "IMG 5767"
    },
    {
      "type": "image",
      "src": "/trips/new-york/IMG_5771.JPG",
      "alt": "IMG 5771"
    },
    {
      "type": "image",
      "src": "/trips/new-york/IMG_5774.jpeg",
      "alt": "IMG 5774"
    },
    {
      "type": "image",
      "src": "/trips/new-york/IMG_5784.jpeg",
      "alt": "IMG 5784"
    }
  ],
  "tokyo": [
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_3D49E25D-0160-4F2E-818F-3AF824C66ACF.jpeg",
      "alt": "IMG 3D49E25D 0160 4F2E 818F 3AF824C66ACF"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_5004.JPG",
      "alt": "IMG 5004"
    },
    {
      "type": "video",
      "src": "/trips/tokyo/IMG_5012.mov",
      "alt": "IMG 5012"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_5015.JPG",
      "alt": "IMG 5015"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_5029.JPG",
      "alt": "IMG 5029"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_5043.JPG",
      "alt": "IMG 5043"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6385.jpeg",
      "alt": "IMG 6385"
    },
    {
      "type": "video",
      "src": "/trips/tokyo/IMG_6387.mov",
      "alt": "IMG 6387"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6401.jpeg",
      "alt": "IMG 6401"
    },
    {
      "type": "video",
      "src": "/trips/tokyo/IMG_6406.mov",
      "alt": "IMG 6406"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6437.jpeg",
      "alt": "IMG 6437"
    },
    {
      "type": "video",
      "src": "/trips/tokyo/IMG_6439.mov",
      "alt": "IMG 6439"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6450.jpeg",
      "alt": "IMG 6450"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6457.jpeg",
      "alt": "IMG 6457"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6464.jpeg",
      "alt": "IMG 6464"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6471.jpeg",
      "alt": "IMG 6471"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6480.jpeg",
      "alt": "IMG 6480"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6483.jpeg",
      "alt": "IMG 6483"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6492.jpeg",
      "alt": "IMG 6492"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6519.jpeg",
      "alt": "IMG 6519"
    },
    {
      "type": "video",
      "src": "/trips/tokyo/IMG_6522.mov",
      "alt": "IMG 6522"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6526.jpeg",
      "alt": "IMG 6526"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6537.jpeg",
      "alt": "IMG 6537"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6561.jpeg",
      "alt": "IMG 6561"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6572.jpeg",
      "alt": "IMG 6572"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6583.jpeg",
      "alt": "IMG 6583"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6585.jpeg",
      "alt": "IMG 6585"
    },
    {
      "type": "image",
      "src": "/trips/tokyo/IMG_6600.jpeg",
      "alt": "IMG 6600"
    }
  ],
  "university-of-illinois": [
    {
      "type": "video",
      "src": "/trips/university-of-illinois/021C9D8C-ACE1-4A64-8D74-BD1DA95E56DF.mov",
      "alt": "C9D8C ACE1 4A64 8D74 BD1DA95E56DF"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/102_4092.JPG",
      "alt": "4092"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/121_2263.JPG",
      "alt": "2263"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/34122192_Unknown.JPG",
      "alt": "Unknown"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_1713.JPG",
      "alt": "IMG 1713"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_1718.JPG",
      "alt": "IMG 1718"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_1725.JPG",
      "alt": "IMG 1725"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_1729.JPG",
      "alt": "IMG 1729"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_1747.JPG",
      "alt": "IMG 1747"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_1755.JPG",
      "alt": "IMG 1755"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_1759.JPG",
      "alt": "IMG 1759"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_1760.JPG",
      "alt": "IMG 1760"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_1781.JPG",
      "alt": "IMG 1781"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_4916.jpeg",
      "alt": "IMG 4916"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_4918.jpeg",
      "alt": "IMG 4918"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_4922.jpeg",
      "alt": "IMG 4922"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_4929.jpeg",
      "alt": "IMG 4929"
    },
    {
      "type": "video",
      "src": "/trips/university-of-illinois/IMG_4930.mov",
      "alt": "IMG 4930"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_4933.jpeg",
      "alt": "IMG 4933"
    },
    {
      "type": "video",
      "src": "/trips/university-of-illinois/IMG_4953.mov",
      "alt": "IMG 4953"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_4957.jpeg",
      "alt": "IMG 4957"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_4966.jpeg",
      "alt": "IMG 4966"
    },
    {
      "type": "video",
      "src": "/trips/university-of-illinois/IMG_4968.mov",
      "alt": "IMG 4968"
    },
    {
      "type": "video",
      "src": "/trips/university-of-illinois/IMG_5002.mov",
      "alt": "IMG 5002"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_5013.JPG",
      "alt": "IMG 5013"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_5109.JPG",
      "alt": "IMG 5109"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_5111.JPG",
      "alt": "IMG 5111"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_5119.JPG",
      "alt": "IMG 5119"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_5121.JPG",
      "alt": "IMG 5121"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_5123.JPG",
      "alt": "IMG 5123"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_5124.JPG",
      "alt": "IMG 5124"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_5128.JPG",
      "alt": "IMG 5128"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_5602.jpeg",
      "alt": "IMG 5602"
    },
    {
      "type": "image",
      "src": "/trips/university-of-illinois/IMG_5606.jpeg",
      "alt": "IMG 5606"
    }
  ],
  "yosemite": [
    {
      "type": "image",
      "src": "/trips/yosemite/IMG_4490.JPG",
      "alt": "IMG 4490"
    },
    {
      "type": "image",
      "src": "/trips/yosemite/IMG_4505.JPG",
      "alt": "IMG 4505"
    },
    {
      "type": "image",
      "src": "/trips/yosemite/IMG_4508.JPG",
      "alt": "IMG 4508"
    },
    {
      "type": "image",
      "src": "/trips/yosemite/IMG_4524.JPG",
      "alt": "IMG 4524"
    },
    {
      "type": "image",
      "src": "/trips/yosemite/IMG_5466.jpeg",
      "alt": "IMG 5466"
    },
    {
      "type": "image",
      "src": "/trips/yosemite/IMG_5474.jpeg",
      "alt": "IMG 5474"
    },
    {
      "type": "image",
      "src": "/trips/yosemite/IMG_5483.jpeg",
      "alt": "IMG 5483"
    },
    {
      "type": "video",
      "src": "/trips/yosemite/IMG_5488.mov",
      "alt": "IMG 5488"
    },
    {
      "type": "image",
      "src": "/trips/yosemite/IMG_5491.jpeg",
      "alt": "IMG 5491"
    },
    {
      "type": "image",
      "src": "/trips/yosemite/IMG_5505.jpeg",
      "alt": "IMG 5505"
    },
    {
      "type": "image",
      "src": "/trips/yosemite/IMG_5514.jpeg",
      "alt": "IMG 5514"
    },
    {
      "type": "video",
      "src": "/trips/yosemite/IMG_5519.mov",
      "alt": "IMG 5519"
    },
    {
      "type": "video",
      "src": "/trips/yosemite/IMG_5523.mov",
      "alt": "IMG 5523"
    },
    {
      "type": "image",
      "src": "/trips/yosemite/IMG_5526.jpeg",
      "alt": "IMG 5526"
    },
    {
      "type": "image",
      "src": "/trips/yosemite/IMG_5562.JPG",
      "alt": "IMG 5562"
    }
  ]
};
